import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { IMessage } from '../interfaces/messages.interface';
import { Observable, of } from 'rxjs';

@Injectable()
export class MessageRestService {
  constructor(private http: HttpClient) {}

  public getMessages(inbox = true): Observable<IMessage[]> {
    return of(
      this.messages.filter(
        (message) => (message.from && inbox) || (message.to && !inbox)
      )
    );
  }

  private messages: IMessage[] = [
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '3',
      to: null,
      from: 'John Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
  ];
}
