import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { IMessage } from '../interfaces/messages.interface';
import { BehaviorSubject, Observable, filter, map, of } from 'rxjs';

@Injectable()
export class MessageRestService {
  public messages$ = new BehaviorSubject<IMessage[]>([]);
  constructor(private http: HttpClient) { }

  public getMessages(inbox = true): Observable<IMessage[]> {
    return of(
      this.messages
    ).pipe(
      map((messages) => {
        this.messages$.next(messages);
        return messages.filter(
          (message) => (message.from && inbox) || (message.to && !inbox)
        )
      }),
    );
  }

  public getMessage(id: string): IMessage | null {
    return this.messages$.value.find((message) => message.id === id) || null;
  }

  private messages: IMessage[] = [
    {
      id: '1',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '2',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '3',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '4',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '5',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '7',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '8',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '9',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '10',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '11',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '12',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '13',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '14',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '15',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '16',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '17',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '18',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '19',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '20',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '21',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '22',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '23',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '24',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '25',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '26',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '27',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '28',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '29',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '30',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '31',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '32',
      to: 'John Doe',
      from: null,
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
    {
      id: '33',
      to: null,
      from: 'Jane Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: true,
    },
    {
      id: '34',
      to: null,
      from: 'John Doe',
      subject: 'Lorem ipsum dolor sit amet',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget turpis nec risus gravida ultrices. Nulla facilisi. Donec nec ligula nec libero vulputate ultrices. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor. Nullam nec nunc vitae elit ultricies tempor.',
      date: '2021-07-01',
      read: false,
    },
  ];
}
